FROM node:20

RUN apt-get update
RUN apt-get install -y git curl

WORKDIR /home/app

COPY main.sh main.sh
COPY script.js script.js
COPY package*.json .

RUN npm install

RUN chmod +x main.sh

ENTRYPOINT ["/home/app/main.sh"]